# Generated by Django 6.0.5 on 2026-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateField()),
                ('page', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
