# Generated by Django 6.0.5 on 2026-08-10 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
