# Generated by Django 6.0.5 on 2026-08-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='tyoe_phone',
            new_name='type_phone',
        ),
    ]
