# Generated by Django 6.0.5 on 2026-08-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('city', models.TextField()),
            ],
        ),
    ]
