# Generated by Django 6.0.5 on 2026-05-26 10:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_watchlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Watchlist",
            new_name="Wishlist",
        ),
        migrations.RenameField(
            model_name="wishlist",
            old_name="product",
            new_name="products",
        ),
    ]
