# Generated by Django 6.0 on 2026-04-29 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField()),
                ('phone', models.CharField()),
                ('about', models.TextField()),
                ('position', models.CharField(choices=[('Manager', 'manager'), ('Software Developer', 'sd'), ('Project leader', 'pd')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.company')),
            ],
        ),
    ]
