# Generated by Django 6.0.5 on 2026-06-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_contact_contact_id_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
