# Generated by Django 6.0.7 on 2026-08-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_book_auther'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('positive_num', models.PositiveIntegerField()),
                ('small_positive_num', models.PositiveSmallIntegerField()),
                ('small_num', models.SmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('cv', models.FileField(upload_to='cv/')),
                ('float_num', models.FloatField()),
                ('generic_IP', models.GenericIPAddressField()),
                ('binary_field', models.BinaryField()),
                ('slug_field', models.SlugField(max_length=200)),
                ('message', models.TextField()),
                ('url', models.URLField()),
                ('time', models.TimeField()),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
